# Generated by Django 6.0.1 on 2026-02-07 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bursary.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='bursary.county'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_no', models.CharField(blank=True, max_length=50, null=True)),
                ('id_copy', models.FileField(blank=True, null=True, upload_to='documents/id/')),
                ('birth_copy', models.FileField(blank=True, null=True, upload_to='documents/birth/')),
                ('disability', models.BooleanField(default=False)),
                ('disability_details', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='documents/fee_structure/')),
                ('academic_performance', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('transcript', models.FileField(blank=True, null=True, upload_to='documents/transcript/')),
                ('level_of_study', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('kmtc', 'KMTC'), ('high', 'High School')], max_length=20)),
                ('polling_station', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_location', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.CharField(blank=True, max_length=255, null=True)),
                ('parents_status', models.CharField(blank=True, choices=[('both_alive', 'Both Alive'), ('mother_alive', 'Mother Alive'), ('father_alive', 'Father Alive'), ('single_mother', 'Single Mother'), ('single_father', 'Single Father'), ('orphan', 'Orphan')], max_length=50, null=True)),
                ('parent_disabled', models.BooleanField(default=False)),
                ('disabled_parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled_parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('disabled_parent_type', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled_parent_doc', models.FileField(blank=True, null=True, upload_to='documents/disabled_parent/')),
                ('siblings_highschool_names', models.TextField(blank=True, null=True)),
                ('siblings_highschool_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('siblings_college_names', models.TextField(blank=True, null=True)),
                ('siblings_college_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('siblings_university_names', models.TextField(blank=True, null=True)),
                ('siblings_university_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referee1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referee1_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referee2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referee2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='bursary.constituency')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='bursary.county')),
            ],
        ),
    ]
