# Generated by Django 6.0.1 on 2026-02-08 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('level_of_study', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('id_no', models.CharField(max_length=20)),
                ('birth_cert_no', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_document', models.FileField(upload_to='documents/')),
                ('gender', models.CharField(max_length=10)),
                ('disability', models.CharField(max_length=5)),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('disability_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('admission_number', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('year_of_study', models.CharField(max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(upload_to='documents/')),
                ('performance', models.CharField(max_length=20)),
                ('transcript', models.FileField(upload_to='documents/')),
                ('polling_station', models.CharField(max_length=200)),
                ('sub_location', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('family_status', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('father_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_id', models.CharField(blank=True, max_length=20, null=True)),
                ('father_death_no', models.CharField(blank=True, max_length=50, null=True)),
                ('father_death_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('mother_death_no', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_death_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('siblings_names', models.TextField(blank=True, null=True)),
                ('siblings_amounts', models.TextField(blank=True, null=True)),
                ('referee1_name', models.CharField(max_length=200)),
                ('referee1_phone', models.CharField(max_length=20)),
                ('referee2_name', models.CharField(max_length=200)),
                ('referee2_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('student_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bursary.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='bursary.county'),
        ),
    ]
