# Generated by Django 6.0.1 on 2026-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('unsuccessful', 'Unsuccessful')], default='pending', max_length=20),
        ),
    ]
