# Generated by Django 6.0.1 on 2026-02-04 14:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConstituencyAdmin',
            new_name='ConstituencyOfficer',
        ),
    ]
