# Generated by Django 6.0.1 on 2026-02-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Fee'),
        ),
    ]
