# Generated by Django 6.0.1 on 2026-02-03 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_constituency_county_levelofstudy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='admin',
            field=models.OneToOneField(blank=True, help_text='Admin for this constituency', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
