# Generated by Django 6.0.1 on 2026-02-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0004_remove_constituency_admin_constituencyadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='student_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='constituencyadmin',
            name='constituency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bursary.constituency'),
        ),
    ]
