# Generated by Django 6.0.1 on 2026-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0005_application_status_application_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admission_number',
            field=models.CharField(max_length=50),
        ),
    ]
